package access

// Code generated from the ShieldNet 360 connector capability matrix
// (ported from the reference docs/connectors.md). DO NOT EDIT by hand:
// regenerate when the matrix changes. The curated rows carry the four
// product-surface dimensions that cannot be derived from the Go type
// system because every connector implements the mandatory AccessConnector
// contract (so a method's mere presence proves nothing about whether the
// upstream provider actually backs the capability). The completeness test
// in capability_descriptor_test.go pins this table against the live
// registry so it can never silently drift from the connectors shipped in
// the binary.

// connectorCatalogData is the curated, per-provider product metadata for
// one connector: its human display name, tier, category, and the five
// user-facing capability flags from the published matrix. Operational
// capability flags (group sync, delta sync, SCIM, ...) are NOT stored here
// — they are derived at lookup time by type-asserting the registered
// connector against the optional interfaces, so they can never drift.
type connectorCatalogData struct {
	DisplayName      string
	Tier             string
	Category         string
	SyncIdentity     bool
	ProvisionAccess  bool
	ListEntitlements bool
	GetAccessLog     bool
	SSOFederation    bool
}

// connectorCatalog maps a registered provider key to its curated catalog
// metadata. Keyed by the exact ProviderName the connector registers under.
var connectorCatalog = map[string]connectorCatalogData{
	"microsoft":         {DisplayName: "Microsoft Entra ID", Tier: "T1", Category: "IAM/SSO", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"google_workspace":  {DisplayName: "Google Workspace", Tier: "T1", Category: "IAM/SSO", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"okta":              {DisplayName: "Okta", Tier: "T1", Category: "IAM/SSO", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"auth0":             {DisplayName: "Auth0", Tier: "T1", Category: "IAM/SSO", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"generic_saml":      {DisplayName: "Generic SAML", Tier: "T1", Category: "IAM/SSO", SyncIdentity: false, ProvisionAccess: false, ListEntitlements: false, GetAccessLog: false, SSOFederation: true},
	"generic_oidc":      {DisplayName: "Generic OIDC", Tier: "T1", Category: "IAM/SSO", SyncIdentity: false, ProvisionAccess: false, ListEntitlements: false, GetAccessLog: false, SSOFederation: true},
	"duo_security":      {DisplayName: "Duo Security", Tier: "T1", Category: "IAM/MFA", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"onepassword":       {DisplayName: "1Password", Tier: "T1", Category: "Secrets/Vault", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"lastpass":          {DisplayName: "LastPass", Tier: "T1", Category: "Secrets/Vault", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"ping_identity":     {DisplayName: "Ping Identity", Tier: "T1", Category: "IAM/SSO", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"aws":               {DisplayName: "AWS IAM", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"azure":             {DisplayName: "Azure RBAC", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"gcp":               {DisplayName: "GCP IAM", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"cloudflare":        {DisplayName: "Cloudflare", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"tailscale":         {DisplayName: "Tailscale", Tier: "T2", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"digitalocean":      {DisplayName: "DigitalOcean", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"heroku":            {DisplayName: "Heroku", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"vercel":            {DisplayName: "Vercel", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"netlify":           {DisplayName: "Netlify", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"vultr":             {DisplayName: "Vultr", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"linode":            {DisplayName: "Linode", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"ovhcloud":          {DisplayName: "OVHcloud", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"alibaba":           {DisplayName: "Alibaba Cloud", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"cloudsigma":        {DisplayName: "CloudSigma", Tier: "T2", Category: "Cloud Infra", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"wasabi":            {DisplayName: "Wasabi", Tier: "T2", Category: "Storage", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"slack":             {DisplayName: "Slack", Tier: "T3", Category: "Collab", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"ms_teams":          {DisplayName: "MS Teams", Tier: "T3", Category: "Collab", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"zoom":              {DisplayName: "Zoom", Tier: "T3", Category: "Collab", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"notion":            {DisplayName: "Notion", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"asana":             {DisplayName: "Asana", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"monday":            {DisplayName: "Monday.com", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"figma":             {DisplayName: "Figma", Tier: "T3", Category: "Design", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"miro":              {DisplayName: "Miro", Tier: "T3", Category: "Whiteboard", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"trello":            {DisplayName: "Trello", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"airtable":          {DisplayName: "Airtable", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"smartsheet":        {DisplayName: "Smartsheet", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"clickup":           {DisplayName: "ClickUp", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"salesforce":        {DisplayName: "Salesforce", Tier: "T3", Category: "CRM", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"hubspot":           {DisplayName: "HubSpot", Tier: "T3", Category: "CRM", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"zoho_crm":          {DisplayName: "Zoho CRM", Tier: "T3", Category: "CRM", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"pipedrive":         {DisplayName: "Pipedrive", Tier: "T3", Category: "CRM", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"dropbox":           {DisplayName: "Dropbox Business", Tier: "T3", Category: "Storage", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"box":               {DisplayName: "Box", Tier: "T3", Category: "Storage", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"egnyte":            {DisplayName: "Egnyte", Tier: "T3", Category: "Storage", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"github":            {DisplayName: "GitHub", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"gitlab":            {DisplayName: "GitLab", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"jira":              {DisplayName: "Atlassian Jira", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"pagerduty":         {DisplayName: "PagerDuty", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"sentry":            {DisplayName: "Sentry", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"terraform":         {DisplayName: "Terraform", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"docker_hub":        {DisplayName: "Docker Hub", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"jfrog":             {DisplayName: "JFrog", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"sonarcloud":        {DisplayName: "SonarCloud", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"circleci":          {DisplayName: "CircleCI", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"travis_ci":         {DisplayName: "Travis CI", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"launchdarkly":      {DisplayName: "LaunchDarkly", Tier: "T3", Category: "DevOps", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"datadog":           {DisplayName: "Datadog", Tier: "T3", Category: "Observability", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"new_relic":         {DisplayName: "New Relic", Tier: "T3", Category: "Observability", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"splunk":            {DisplayName: "Splunk Cloud", Tier: "T3", Category: "Observability", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"grafana":           {DisplayName: "Grafana", Tier: "T3", Category: "Observability", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"mezmo":             {DisplayName: "Mezmo", Tier: "T3", Category: "Observability", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"manual":            {DisplayName: "Manual / Offline Target", Tier: "T1", Category: "Manual", SyncIdentity: false, ProvisionAccess: true, ListEntitlements: false, GetAccessLog: false, SSOFederation: false},
	"sumo_logic":        {DisplayName: "Sumo Logic", Tier: "T3", Category: "Observability", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"zendesk":           {DisplayName: "Zendesk", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"freshdesk":         {DisplayName: "Freshdesk", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"helpscout":         {DisplayName: "Help Scout", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"front":             {DisplayName: "Front", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"intercom":          {DisplayName: "Intercom", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"drift":             {DisplayName: "Drift", Tier: "T3", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"crisp":             {DisplayName: "Crisp", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"livechat":          {DisplayName: "LiveChat", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"gorgias":           {DisplayName: "Gorgias", Tier: "T3", Category: "Support", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"loom":              {DisplayName: "Loom", Tier: "T3", Category: "Collab", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"discord":           {DisplayName: "Discord", Tier: "T3", Category: "Collab", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"slack_enterprise":  {DisplayName: "Slack Enterprise", Tier: "T3", Category: "Collab", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"basecamp":          {DisplayName: "Basecamp", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"quip":              {DisplayName: "Quip", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"wrike":             {DisplayName: "Wrike", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"teamwork":          {DisplayName: "Teamwork", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"liquidplanner":     {DisplayName: "LiquidPlanner", Tier: "T3", Category: "Productivity", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"knowbe4":           {DisplayName: "KnowBe4", Tier: "T3", Category: "Security Training", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"bamboohr":          {DisplayName: "BambooHR", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"gusto":             {DisplayName: "Gusto", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"rippling":          {DisplayName: "Rippling", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"personio":          {DisplayName: "Personio", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"hibob":             {DisplayName: "Hibob", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"workday":           {DisplayName: "Workday", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"paychex":           {DisplayName: "Paychex", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"deel":              {DisplayName: "Deel", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"zenefits":          {DisplayName: "Zenefits", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"namely":            {DisplayName: "Namely", Tier: "T4", Category: "HR", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"quickbooks":        {DisplayName: "QuickBooks Online", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"xero":              {DisplayName: "Xero", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"stripe":            {DisplayName: "Stripe", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"paypal":            {DisplayName: "PayPal", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"billdotcom":        {DisplayName: "Bill.com", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"expensify":         {DisplayName: "Expensify", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"sage_intacct":      {DisplayName: "Sage Intacct", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"freshbooks":        {DisplayName: "FreshBooks", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"wave":              {DisplayName: "Wave", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"plaid":             {DisplayName: "Plaid", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"brex":              {DisplayName: "Brex", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"ramp":              {DisplayName: "Ramp", Tier: "T4", Category: "Finance", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"clio":              {DisplayName: "Clio", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"ironclad":          {DisplayName: "Ironclad", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"docusign":          {DisplayName: "DocuSign", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"docusign_clm":      {DisplayName: "DocuSign CLM", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"mycase":            {DisplayName: "MyCase", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"pandadoc":          {DisplayName: "PandaDoc", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"pandadoc_clm":      {DisplayName: "PandaDoc CLM", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"hellosign":         {DisplayName: "HelloSign", Tier: "T4", Category: "Legal", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"gong":              {DisplayName: "Gong", Tier: "T4", Category: "Sales", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"salesloft":         {DisplayName: "Salesloft", Tier: "T4", Category: "Sales", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"apollo":            {DisplayName: "Apollo.io", Tier: "T4", Category: "Sales", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"copper":            {DisplayName: "Copper", Tier: "T4", Category: "Sales", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"insightly":         {DisplayName: "Insightly", Tier: "T4", Category: "Sales", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"close":             {DisplayName: "Close", Tier: "T4", Category: "Sales", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"mailchimp":         {DisplayName: "Mailchimp", Tier: "T4", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"klaviyo":           {DisplayName: "Klaviyo", Tier: "T4", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"activecampaign":    {DisplayName: "ActiveCampaign", Tier: "T4", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"constant_contact":  {DisplayName: "Constant Contact", Tier: "T4", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"braze":             {DisplayName: "Braze", Tier: "T4", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"mixpanel":          {DisplayName: "Mixpanel", Tier: "T4", Category: "Analytics", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"segment":           {DisplayName: "Segment", Tier: "T4", Category: "CDP", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"typeform":          {DisplayName: "Typeform", Tier: "T4", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"surveymonkey":      {DisplayName: "SurveyMonkey", Tier: "T4", Category: "Marketing", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"eventbrite":        {DisplayName: "Eventbrite", Tier: "T4", Category: "Events", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"navan":             {DisplayName: "Navan", Tier: "T4", Category: "Travel", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"sap_concur":        {DisplayName: "SAP Concur", Tier: "T4", Category: "Supply", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"coupa":             {DisplayName: "Coupa", Tier: "T4", Category: "Supply", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"anvyl":             {DisplayName: "Anvyl", Tier: "T4", Category: "Supply", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"meraki":            {DisplayName: "Cisco Meraki", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"fortinet":          {DisplayName: "Fortinet", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"zscaler":           {DisplayName: "Zscaler", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"checkpoint":        {DisplayName: "Check Point", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"paloalto":          {DisplayName: "Palo Alto Prisma", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"nordlayer":         {DisplayName: "NordLayer", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"perimeter81":       {DisplayName: "Perimeter 81", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"netskope":          {DisplayName: "Netskope", Tier: "T5", Category: "Network", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"sophos_central":    {DisplayName: "Sophos Central", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"sophos_xg":         {DisplayName: "Sophos XG", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"crowdstrike":       {DisplayName: "CrowdStrike", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"sentinelone":       {DisplayName: "SentinelOne", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"snyk":              {DisplayName: "Snyk", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"hackerone":         {DisplayName: "HackerOne", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"hibp":              {DisplayName: "HIBP", Tier: "T5", Category: "Security", SyncIdentity: false, ProvisionAccess: false, ListEntitlements: false, GetAccessLog: true, SSOFederation: false},
	"bitsight":          {DisplayName: "BitSight", Tier: "T5", Category: "Security", SyncIdentity: false, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"tenable":           {DisplayName: "Tenable.io", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"qualys":            {DisplayName: "Qualys VMDR", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"rapid7":            {DisplayName: "Rapid7", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"virustotal":        {DisplayName: "VirusTotal", Tier: "T5", Category: "Security", SyncIdentity: false, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"malwarebytes":      {DisplayName: "Malwarebytes", Tier: "T5", Category: "Security", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"forgerock":         {DisplayName: "ForgeRock", Tier: "T5", Category: "IAM", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"beyondtrust":       {DisplayName: "BeyondTrust", Tier: "T5", Category: "IAM/PAM", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"keeper":            {DisplayName: "Keeper", Tier: "T5", Category: "Secrets/Vault", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"wazuh":             {DisplayName: "Wazuh", Tier: "T5", Category: "SIEM", SyncIdentity: false, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"openai":            {DisplayName: "OpenAI (ChatGPT)", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"gemini":            {DisplayName: "Google Gemini", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"anthropic":         {DisplayName: "Anthropic (Claude)", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"perplexity":        {DisplayName: "Perplexity AI", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"mistral":           {DisplayName: "Mistral AI", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"midjourney":        {DisplayName: "Midjourney", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"jasper":            {DisplayName: "Jasper AI", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"copyai":            {DisplayName: "Copy.ai", Tier: "T5", Category: "GenAI", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"practice_fusion":   {DisplayName: "Practice Fusion", Tier: "T5", Category: "Health", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"kareo":             {DisplayName: "Kareo", Tier: "T5", Category: "Health", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"zocdoc":            {DisplayName: "Zocdoc", Tier: "T5", Category: "Health", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"yardi":             {DisplayName: "Yardi", Tier: "T5", Category: "Real Estate", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"buildium":          {DisplayName: "Buildium", Tier: "T5", Category: "Real Estate", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"appfolio":          {DisplayName: "AppFolio", Tier: "T5", Category: "Real Estate", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"netsuite":          {DisplayName: "NetSuite", Tier: "T5", Category: "ERP", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"coursera":          {DisplayName: "Coursera", Tier: "T5", Category: "Education", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"linkedin_learning": {DisplayName: "LinkedIn Learning", Tier: "T5", Category: "Training", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"udemy_business":    {DisplayName: "Udemy Business", Tier: "T5", Category: "Training", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"shopify":           {DisplayName: "Shopify", Tier: "T5", Category: "E-comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"woocommerce":       {DisplayName: "WooCommerce", Tier: "T5", Category: "E-comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"bigcommerce":       {DisplayName: "BigCommerce", Tier: "T5", Category: "E-comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"magento":           {DisplayName: "Magento", Tier: "T5", Category: "E-comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"square":            {DisplayName: "Square", Tier: "T5", Category: "E-comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"recurly":           {DisplayName: "Recurly", Tier: "T5", Category: "E-comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"chargebee":         {DisplayName: "Chargebee", Tier: "T5", Category: "E-comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"wordpress":         {DisplayName: "WordPress", Tier: "T5", Category: "Web", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"squarespace":       {DisplayName: "Squarespace", Tier: "T5", Category: "Web", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"wix":               {DisplayName: "Wix", Tier: "T5", Category: "Web", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"ghost":             {DisplayName: "Ghost", Tier: "T5", Category: "Web", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"surveysparrow":     {DisplayName: "SurveySparrow", Tier: "T5", Category: "Customer-Feedback", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"jotform":           {DisplayName: "Jotform", Tier: "T5", Category: "Customer-Feedback", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"wufoo":             {DisplayName: "Wufoo", Tier: "T5", Category: "Customer-Feedback", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"hootsuite":         {DisplayName: "Hootsuite", Tier: "T5", Category: "Social", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"sprout_social":     {DisplayName: "Sprout Social", Tier: "T5", Category: "Social", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"buffer":            {DisplayName: "Buffer", Tier: "T5", Category: "Social", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"twilio":            {DisplayName: "Twilio", Tier: "T5", Category: "Comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"sendgrid":          {DisplayName: "SendGrid", Tier: "T5", Category: "Comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"ringcentral":       {DisplayName: "RingCentral", Tier: "T5", Category: "Comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"vonage":            {DisplayName: "Vonage", Tier: "T5", Category: "Comm", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"zapier":            {DisplayName: "Zapier", Tier: "T5", Category: "Utility", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"make":              {DisplayName: "Make", Tier: "T5", Category: "Utility", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"ifttt":             {DisplayName: "IFTTT", Tier: "T5", Category: "Utility", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: false},
	"ga4":               {DisplayName: "GA4", Tier: "T5", Category: "Analytics", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"heap":              {DisplayName: "Heap", Tier: "T5", Category: "Analytics", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
	"fullstory":         {DisplayName: "FullStory", Tier: "T5", Category: "Analytics", SyncIdentity: true, ProvisionAccess: true, ListEntitlements: true, GetAccessLog: true, SSOFederation: true},
}
